### PR TITLE
src/configure: Add FreeBSD

### PR DESCRIPTION
**Pull request by jlduran**
Add FreeBSD to `src/configure`.

### CODE REVIEW

**Comment by mislav** [comment]
Nice, thanks! Does this work for you when compiling rbenv's native extensions? Test with:

```
cd ~/.rbenv
src/configure
make -C src

RBENV_NATIVE_EXT=1 rbenv version
```

**Comment by jlduran** [comment]
Yes!

**Comment by jlduran** [comment]
`system (set by /home/vagrant/.rbenv/version)`

To reproduce:
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = 'freebsd/FreeBSD-11.0-BETA4'
  config.vm.hostname = 'freebsd'
  config.vm.base_mac = '589CFC000001' # FreeBSD Bug 201904
  config.vm.network 'private_network', ip: '192.168.50.4'
  config.vm.synced_folder '.', '/vagrant', type: 'nfs'
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--nictype1', 'virtio']
    vb.customize ['modifyvm', :id, '--nictype2', 'virtio']
  end

  config.ssh.shell = 'sh'

  config.vm.provision 'shell', inline: <<-ROOT
    pkg upgrade -y
    pkg install -y bash git-lite

    # Bash configuration
    mount -t fdescfs fdesc /dev/fd
    echo 'fdesc		/dev/fd		fdesc	fs	rw	0	0' >> /etc/fstab

    # Prepare the vagrant user:
    # Change its default shell to Bash
    pw usermod vagrant -s /usr/local/bin/bash
  ROOT

  config.vm.provision 'shell', privileged: false, inline: <<-VAGRANT
    # Clone the repo
    git clone https://github.com/jlduran/rbenv.git ~/.rbenv

    # Compile
    cd ~/.rbenv
    git checkout add-freebsd-to-configure-c-extensions
    src/configure
    make -C src

    # Set up .bash_profile
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
    echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
    . ~/.bash_profile

    # Test
    RBENV_NATIVE_EXT=1 rbenv version
  VAGRANT
end
```

**Comment by jlduran** [comment]
@mislav Is there anything blocking this PR?

**Comment by mislav** [comment]
Absolutely nothing! Sorry for the delay.

**Pull request merged**
