### PR TITLE
Fix error about symbolic link

### PR DESCRIPTION
**Pull request by mengbo**
Fix error about symbolic link https://github.com/yyuu/pyenv/pull/502

### CODE REVIEW

**Comment by mislav** [comment]
Thanks for the fix! Could this come with a test that fails without a fix? Otherwise it's hard to tell whether this fixes anything.

**Comment by blueyed** [comment]
I came up with another fix in https://github.com/rbenv/rbenv/pull/868 - which might be more performant?!

But it's also missing a test.

**Comment by blueyed** [comment]
Where should the test go?

**Comment by mislav** [comment]
Closing as wontfix since I'm not sure what this actually fixes.

**Pull request closed without merging**
