### PR TITLE
Speed up shims

### PR DESCRIPTION
**Pull request by marcthe12**
Solves #1100

### CODE REVIEW

**Comment by marcthe12** [comment]
Need help on understanding test 13:
`# (from function `flunk' in file test/test_helper.bash, line 42,
#  from function `assert_success' in file test/test_helper.bash, line 47,
#  in test file test/exec.bats, line 108)
#   `assert_success "hello rake"' failed`

This test trips the changes. I do not use ruby -S ever so I do not what is the source of the error

**Comment by hsbt** [comment]
Can you show the measurement results with your improvement?

**Comment by marcthe12** [comment]
`
$ /bin/time -v gem -v
2.7.7
        Command being timed: "gem -v"
        User time (seconds): 0.30
        System time (seconds): 0.09
        Percent of CPU this job got: 101%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.39
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 11096
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 11485
        Voluntary context switches: 135
        Involuntary context switches: 74
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0

$ /bin/time -v gem -v
2.7.7
        Command being timed: "gem -v"
        User time (seconds): 0.26
        System time (seconds): 0.07
        Percent of CPU this job got: 102%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.33
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 10928
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 11666
        Voluntary context switches: 153
        Involuntary context switches: 56
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
`

**Comment by mislav** [comment]
Sorry, but this breaks `ruby -S` and doesn't give us much apart from 6ms improvement, which I don't think is worth a breaking change.

**Comment by marcthe12** [comment]
Actually it also makes rbenv exec $COMMAND same as $COMMAND as side effect. That can be helpfull too. Idealy the shims should be just
`#!/usr/bin/env

exec rbenv exec $program" "$@"
`

**Comment by marcthe12** [comment]
Replaced by  #1109.

**Pull request closed without merging**
